import time
import sys
import pytest
import stripe
from subscribie.settings import settings
from uuid import uuid4
from subscribie import create_app
from subscribie.logger import logger
import subprocess


_STRIPE_TEST_KEY = settings.get("STRIPE_TEST_SECRET_KEY") or ""


@pytest.mark.skipif(
    not _STRIPE_TEST_KEY or "changeme" in _STRIPE_TEST_KEY,
    reason=(
        "Requires a real STRIPE_TEST_SECRET_KEY. The placeholder "
        "'sk_test_changeme' from settings.yaml.example is in use, so this "
        "test would call the live Stripe API and 401. Run locally with a "
        "real key to exercise the Stripe test-clock path."
    ),
)
def test_draft_invoices_get_application_fee_amount_applied():
    """
    Verify that future draft invoices generated by existing (and active)
    Stripe Subscriptions have the correct application_fee_amount applied.
    Related issue: https://github.com/Subscribie/subscribie/pull/1465
    """

    subprocess.run("./stop_stripe_listener.sh", shell=True)
    subprocess.run("./start_stripe_listener.sh", shell=True)

    stripe.api_key = settings.get("STRIPE_TEST_SECRET_KEY")

    logger.info("=== Stripe Test Clock Simulation ===")

    # 1. Start the clock at a specific frozen time (e.g., today's timestamp)
    now_unix = int(time.time())

    try:
        # 2. Create a Connected Account for testing
        logger.info("2. Creating Test Connected Account")
        account = stripe.Account.create(
            type="standard",
            country="GB",
            email="test_connect@subscribie.co.uk",
        )
        logger.info(f"   -> Account ID: {account.id}")

        logger.info(f"3. Creating Test Clock frozen at: {now_unix}")
        clock = stripe.test_helpers.TestClock.create(
            frozen_time=now_unix,
            name="Subscribie Webhook Confidence Test",
            stripe_account=account.id,
        )
        logger.info(f"   -> Clock ID: {clock.id}")

        # 4. Create a Customer attached to the Test Clock
        logger.info("4. Creating Test Customer attached to the clock")
        customer = stripe.Customer.create(
            email="clock_test@subscribie.co.uk",
            test_clock=clock.id,
            payment_method="pm_card_visa",
            invoice_settings={"default_payment_method": "pm_card_visa"},
            stripe_account=account.id,
        )
        logger.info(f"   -> Customer ID: {customer.id}")

        # 5. Create a Product and Recurring Price on the connected account
        logger.info(
            "5. Creating Test Product & Price on Connected Account (50 GBP/month)"
        )
        product = stripe.Product.create(
            name="Subscribie Test Plan", stripe_account=account.id
        )
        price = stripe.Price.create(
            product=product.id,
            unit_amount=5000,
            currency="gbp",
            recurring={"interval": "month"},
            stripe_account=account.id,
        )
        logger.info(f"   -> Price ID: {price.id}")

        logger.info("6. Creating Subscription")
        subscribie_checkout_session_id = (
            f"test_session_id_for_stipe_test_clock_simulation-{uuid4()}"
        )
        subscription = stripe.Subscription.create(
            customer=customer.id,
            items=[{"price": price.id}],
            application_fee_percent=2.5,  # Mimic exactly what the checkout does
            stripe_account=account.id,
            metadata={
                "subscribie_checkout_session_id": subscribie_checkout_session_id,
                "person_uuid": customer.id,
            },
        )
        logger.info(f"   -> Subscription ID: {subscription.id}")

        # To prevent the Webhook
        # "Empty metadata" and throwing a 422
        # on `payment_intent_succeeded`, we need to mock a local
        # Subscription in the DB
        try:
            from subscribie.database import database
            from subscribie.models import Person, Subscription

            app = create_app()

            with app.app_context():
                person_uuid = customer.id
                person = Person(
                    email="clock_test@example.co.uk",
                    password="fake",
                    uuid=person_uuid,
                )
                database.session.add(person)
                database.session.commit()

                sub = Subscription(
                    uuid=str(uuid4()),
                    subscribie_checkout_session_id=subscribie_checkout_session_id,
                    person_id=person.id,
                )
                database.session.add(sub)
                database.session.commit()
        except Exception as e:
            logger.info(
                "   -> Warning: Failed to mock local DB records. "
                f"(Webhook may report Empty metadata): {e}"
            )

        # 7. Advance the clock by exactly 1 month!
        # This simulates a "subscription_cycle" renewal
        advance_to = now_unix + (31 * 24 * 60 * 60)  # roughly 31 days
        logger.info(
            f"\n7. ADVANCING CLOCK to {advance_to} (simulating 1 month passing)"
        )

        stripe.test_helpers.TestClock.advance(
            clock.id, frozen_time=advance_to, stripe_account=account.id
        )

        logger.info("   -> Waiting for Stripe Test Clock to advance...")
        logger.info(
            "   -> (Stripe takes 1-2 minutes of real-world time to compute a "
            "simulated month of billing logic in the background.)"
        )
        clock_ready = False
        attempts = 0
        while not clock_ready and attempts < 30:
            attempts += 1
            clock_status = stripe.test_helpers.TestClock.retrieve(
                clock.id, stripe_account=account.id
            )
            if clock_status.status == "ready":
                clock_ready = True
                logger.info(
                    "   [SUCCESS] Stripe Test Clock is 'ready'. The simulation "
                    "reached the specified future time."
                )
                break
            logger.info(
                "   ... Waiting... Clock status is currently "
                f"'{clock_status.status}' because Stripe is still "
                "processing billing events. (Attempt {attempts}/30)..."
            )
            time.sleep(5)

        if not clock_ready:
            logger.error(
                "   [ERROR] Stripe Test Clock timed out after 150 seconds. Exiting."
            )
            exit(1)

        # Give the webhook a moment to process after clock is ready
        logger.info(
            "   -> Giving local webhook 5 seconds to receive the forwarded "
            "invoice payload..."
        )
        time.sleep(5)

        # 8. Check the newly generated invoice
        logger.info("\n8. Fetching the newly generated renewal invoice from Stripe...")

        # Poll Stripe until the new invoice appears, and wait for webhook modification
        found_and_modified = False
        attempts = 0
        while not found_and_modified and attempts < 10:
            attempts += 1
            invoices = stripe.Invoice.list(
                subscription=subscription.id, limit=3, stripe_account=account.id
            )

            cycle_invoice_found = False
            for inv in invoices.data:
                if inv.billing_reason == "subscription_cycle":
                    cycle_invoice_found = True
                    logger.info(f"   --- Attempt {attempts}/10 ---")
                    logger.info(f"   Invoice ID: {inv.id}")
                    logger.info(f"   Status: {inv.status}")

                    if inv.status == "draft":
                        fee = getattr(inv, "application_fee_amount", None)
                        if fee is not None:
                            logger.info(
                                "   [SUCCESS] End-to-End verified! Local "
                                f"webhook caught the '{inv.status}' invoice "
                                f"and successfully injected "
                                "application_fee_amount: {fee}"
                            )
                            found_and_modified = True
                            break
                        else:
                            logger.info(
                                f"   [PENDING] Invoice is generated as "
                                f"'{inv.status}', but missing the new fee. "
                                "Waiting for 'stripe listen' to trigger your "
                                "local Flask webhook handler..."
                            )
                    else:
                        logger.info(
                            "   [WARNING] The renewal invoice is "
                            f"'{inv.status}'. Stripe finalized it before the"
                            "webhook could modify it! Timing issue exists."
                        )
                        found_and_modified = True  # Ensure we exit the loop
                        break

            if not found_and_modified:
                if not cycle_invoice_found:
                    logger.info(
                        "   ... Waiting for Stripe to formulate the "
                        "'subscription_cycle' renewal invoice (Attempt "
                        f"{attempts}/10)..."
                    )
                time.sleep(5)

    finally:
        # Cleanup
        if "clock" in locals() and "account" in locals():
            logger.info("\n9. Cleaning up Test Clock from Stripe account...")
            stripe.test_helpers.TestClock.delete(clock.id, stripe_account=account.id)
            logger.info("   -> Done.")

        if "subscribie.logger" in sys.modules and hasattr(
            sys.modules["subscribie.logger"], "listener"
        ):
            sys.modules["subscribie.logger"].listener.stop()
