"""create chosen_option table

Revision ID: 4a72413f3d7a
Revises: 69199ce31c96
Create Date: 2020-08-08 15:54:24.932195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a72413f3d7a'
down_revision = '69199ce31c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chosen_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('choice_group_id', sa.Integer(), nullable=True),
    sa.Column('choice_group_title', sa.String(), nullable=True),
    sa.Column('option_title', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    pass
