"""add LoginToken model

Revision ID: 500f2d55c5d3
Revises: fd28aefcdb76
Create Date: 2021-02-13 00:04:37.827539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "500f2d55c5d3"
down_revision = "fd28aefcdb76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_token",
        sa.Column("user_uuid", sa.String(), nullable=False),
        sa.Column("login_token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("login_token")
    # ### end Alembic commands ###
