"""subscription to document association

Revision ID: 938b171f97ec
Revises: 429b32b9ad20
Create Date: 2022-11-19 22:56:16.153807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "938b171f97ec"
down_revision = "429b32b9ad20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_document_associations",
        sa.Column("subscription_uuid", sa.String(), nullable=False),
        sa.Column("document_uuid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_uuid"],
            ["document.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_uuid"],
            ["subscription.uuid"],
        ),
    )


def downgrade():
    pass
