"""add uuid to person table

Revision ID: c01359894f1d
Revises: e8ba76bdb645
Create Date: 2020-04-23 20:42:59.386440

"""
from alembic import op
import sqlalchemy as sa
from uuid import uuid4


# revision identifiers, used by Alembic.
revision = 'c01359894f1d'
down_revision = 'e8ba76bdb645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person") as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person") as batch_op:
        batch_op.drop_column('uuid')
    # ### end Alembic commands ###
