name: Auto create git branch upon new issue
on:
  issues:
    types: [opened, reopened]

jobs:
  create-issue-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get issue number and title
        id: issue
        run: |
          echo "::set-output name=number::${{ github.event.issue.number }}"
          echo "::set-output name=title::${{ github.event.issue.title }}"
          # Sanitize issue title to create a valid git branch name:
          # 1. Replace all non-alphanumeric characters with hyphens
          # 2. Replace multiple consecutive hyphens with a single hyphen
          # 3. Remove leading and trailing hyphens
          # 4. Convert all uppercase letters to lowercase
          # 5. Truncate the string to a maximum of 60 characters
          # 6. Remove any trailing hyphen that might have resulted from truncation
          ISSUE_BRANCH_NAME=$(echo "${{ github.event.issue.title }}" \
            | sed 's/[^a-zA-Z0-9]/-/g' \
            | sed 's/-\+/-/g' \
            | sed 's/^-//;s/-$//' \
            | tr '[:upper:]' '[:lower:]' \
            | cut -c -60 \
            | sed 's/-$//')
          echo "ISSUE_BRANCH_NAME=$ISSUE_BRANCH_NAME" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          echo "The issue branch name is ${{ env.ISSUE_BRANCH_NAME}} "
          git checkout -b "${{ steps.issue.outputs.number }}-${{ env.ISSUE_BRANCH_NAME }}"
          git push -u origin HEAD

      - name: Create Empty Commit to allow empty pr
        run: |
          git config --global user.name "nobody"
          git config --global user.email "username@users.noreply.github.com"
          git commit --allow-empty -m "Empty commit to allow auto PR creation"
          git fetch origin
          git rebase --strategy-option=theirs origin/master --verbose # thanks https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html
          git push --verbose
  
      - name: Creating PR based on branch name ${{ github.ref_name }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Subscribie/subscribie/pulls \
          -d '{"title": "#${{ steps.issue.outputs.number }} ${{ env.ISSUE_BRANCH_NAME }}","body":"Pull request related issue: #${{ steps.issue.outputs.number }}. Please pull these awesome changes in!","head":"${{ steps.issue.outputs.number }}-${{ env.ISSUE_BRANCH_NAME }}","base":"master"}'
