name: Deploy to production
on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
jobs:
  deploy_prod:
    name: Deploy to prod
    environment:
      name: Production
    runs-on: ubuntu-20.04
    steps:
    - name: Setup ssh access
      run: |
        set -x
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.ONBOARDING_PRIVATE_KEY }}"
        ssh-keyscan ${{ secrets.ONBOARDING_HOST }}>> ~/.ssh/known_hosts
    - name: Pull new site
      run: |
        set -x
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.ONBOARDING_PRIVATE_KEY }}"
        ssh ${{ secrets.ONBOARDING_USER }}@${{ secrets.ONBOARDING_HOST }} -C \
          "set -x \
          cd /home/subwebbuild/www/subscriptionwebsitebuilder.co.uk/subscribie; \
          pwd &&\
          git fetch; git rebase origin/master \
          . venv/bin/activate; \
          pip install -r requirements.txt; \
          export FLASK_APP=subscribie; \
          flask db upgrade"
    - name: Reload apache
      run: |
        set -x
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.ONBOARDING_PRIVATE_KEY }}"
        ssh ${{ secrets.ONBOARDING_USER }}@${{ secrets.ONBOARDING_HOST }} -C "sudo /etc/init.d/apache2 reload"
    - name: Smoke test
      run: |
        curl --fail -v https://subscriptionwebsitebuilder.co.uk
