---
name: Install Stripe cli
on: 
  push:
    branches: [ videos-of-tests ]
jobs:
  install-stripe-cli:
    runs-on: ubuntu-20.04
    environment: testing
    steps:
      - name: Install Stripe cli 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          curl -OL https://github.com/stripe/stripe-cli/releases/download/v1.5.5/stripe_1.5.5_linux_amd64.deb
          sudo dpkg -i stripe_1.5.5_linux_amd64.deb
          mkdir -p /home/runner/.config/stripe/
          touch /home/runner/.config/stripe/config.toml
          stripe config --set test_mode_api_key ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          stripe config --set test_mode_publishable_key ${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}
          stripe listen --forward-to 127.0.0.1:5000/stripe_webhook 2> >(tee out.txt >&2)& echo "Waiting for webhook signing secret"; sleep 5;WHSEC=`egrep -o 'whsec_([A-Za-z]|[0-9])*' out.txt`;
          echo $WHSEC
          jobs

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install node dependencies
        run: npm install
