name: Update Onboarding Site
on:
  workflow_dispatch:
  push:
    paths:
    - 'subscribie/themes/theme-builder/**'
jobs:
  update_onboarding:
    name: Update onboarding
    runs-on: ubuntu-20.04
    steps:
    - name: Pull new site
      run: |
        set -x
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.ONBOARDING_PRIVATE_KEY }}"
        ssh-keyscan $ONBOARDING_HOST>> ~/.ssh/known_hosts

