name: Update Onboarding Site
on:
  workflow_dispatch:
  push:
    paths:
    - 'subscribie/themes/theme-builder/**'
    paths-ignore:
      - '**/README.md'
      - '**/TESTING.md'
jobs:
  update_onboarding:
    name: Update onboarding
    runs-on: ubuntu-20.04
    steps:
    - name: Setup ssh access
      run: |
        set -x
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.ONBOARDING_PRIVATE_KEY }}"
        ssh-keyscan ${{ secrets.ONBOARDING_HOST }}>> ~/.ssh/known_hosts
    - name: Pull new site & reload
      run: |
        set -x
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.UPDATE_ALL_SITES_PRIVATE_KEY}}"
        ssh ${{ secrets.ONBOARDING_USER }}@${{ secrets.ONBOARDING_HOST }} -C "cd ${{ secrets.SHAREDREPO_PATH }}; git fetch; git rebase origin/master;"
        ssh ${{ secrets.ONBOARDING_USER }}@${{ secrets.ONBOARDING_HOST }} -C "cd ${{ secrets.ONBOARDING_WEBSITE_PATH }}; touch *.ini; "

