name: Update Onboarding Site
on:
  push:
    paths:
    - 'subscribie/themes/theme-builder/**'
jobs:
  update_onboarding:
    name: Update onboarding
    runs-on: ubuntu-20.04
    steps:
    - name: Pull new site
      run: echo "Test"
