name: Update Docs
on:
  workflow_dispatch:
  push:
    branches:
      - 990-docs-as-part-of-release-hugo
jobs:
  update_all_sites:
    name: Update Docs
    runs-on: ubuntu-20.04
    steps:
    - name: Setup ssh access
      run: |
        set -x
        mkdir -p ~/.ssh
        eval `ssh-agent -s` 
        ssh-add - <<< "${{ secrets.UPDATE_ALL_SITES_PRIVATE_KEY}}"
        ssh-keyscan ${{ secrets.ONBOARDING_HOST }}>> ~/.ssh/known_hosts
    - name: Installing Hugo
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install hugo --channel=extended
    - name: moving html files into the server
      run: |
        set -x
        eval `ssh-agent -s` 
        ssh-add - <<< "${{ secrets.UPDATE_ALL_SITES_PRIVATE_KEY}}"
        cd ${{ secrets.REPO_DOCS_PATH }}
        hugo
        ssh ${{ secrets.ONBOARDING_USER }}@${{ secrets.ONBOARDING_HOST }} -C "rm -r ${{ secrets.DOCS_PATH }}/public/"
        scp -r public/ ${{ secrets.ONBOARDING_USER }}@${{ secrets.ONBOARDING_HOST }}:${{ secrets.DOCS_PATH }}/public/
