name: Verify Container Builds
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  verify_container_builds:
    name: Verify container builds
    environment:
      name: testing
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build container
      run: |
        cp .env.example .env
        export COMPOSE_DOCKER_CLI_BUILD=1
        export DOCKER_BUILDKIT=1
        docker build -t test .
